# Generated by Django 2.2.3 on 2019-11-10 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='title',
            new_name='firstName',
        ),
        migrations.RemoveField(
            model_name='form',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='form',
            name='description',
        ),
        migrations.AddField(
            model_name='form',
            name='lastName',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        
        migrations.AddField(
            model_name='form',
            name='telephone',
            field=models.CharField(default=8888888, max_length=120),
            preserve_default=False,
        ),
    ]
