# Generated by Django 2.2.3 on 2019-11-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20191110_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
