# Generated by Django 2.2.7 on 2019-11-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_form_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='CityMobil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='GetTaxi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='Uber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='Yandex',
            field=models.BooleanField(default=False),
        ),
    ]
