# Generated by Django 2.2.7 on 2019-11-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20191115_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='size',
            new_name='size_of_picture',
        ),
    ]
