# Generated by Django 2.2.7 on 2019-11-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20191115_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='size',
            new_name='size_of_picture',
        ),
    ]
